### ISSUE TITLE
The game is not updated on the client when another player's move

### ISSUE THREAD

**Issue by igavva** [lky1001/eos-tic-tac-toe#1]
Hi. The game is not updated on the client when another player's move. How to fix? Can I use setInterval to update the GameInfo? Thanks in advance)

**Comment by igavva** [comment]
createGame = () => {
        this.setState({
            isLoading: true
        });

        this.getGameInfo();

        this.timerID = setInterval(
            () => this.getGameInfo(),
            1000
        );
    };

**Comment by lky1001** [comment]
@igavva Hi,
Check into move function (https://github.com/lky1001/eos-tic-tac-toe/blob/7c44ef0e36529d578b8449f63199cb65359efa63/src/pages/Game.js#L176)

Update the gameinfo after move action.

**Comment by igavva** [comment]
@lky1001 Hi) I checked it) Play the game on two tabs. Alice and Bob play this game. Alice sends a move message and updates the game state (getGameInfo). Bob's game state is not updated.

**Comment by lky1001** [comment]
@igavva Oh, I understand.

I am not considering playing on two tabs.

I will fix. 

Thanks.
